In [1]:
import pandas as pd

df = pd.read_csv('20230721-DDSales.txt', sep='\t', parse_dates=['Sales Date', 'Report Date'])
df.head()

/var/folders/gk/d8kt9wwn7mx9mw4x20przb4w0000gn/T/ipykernel_33871/3925997829.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv('20230721-DDSales.txt', sep='\t', parse_dates=['Sales Date', 'Report Date'])
/var/folders/gk/d8kt9wwn7mx9mw4x20przb4w0000gn/T/ipykernel_33871/3925997829.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv('20230721-DDSales.txt', sep='\t', parse_dates=['Sales Date', 'Report Date'])

,Report Date,Sales Date,Quantity,Price,Subtotal,Isrc,Barcode,CDBabySku,Album Name,Artist Name,Track Name,Partner Name,Transaction Type,Delivery Country
0,2017-10-16,2017-08-15,7.0,0.000773,0.005415,ushm21787661,191924100799,infinitygirl,Stop Being on My Side,Infinity Girl,Walking Around,Pandora Radio,Stream,US
1,2017-10-16,2017-08-15,1.0,0.000773,0.000773,ushm21787664,191924100799,infinitygirl,Stop Being on My Side,Infinity Girl,By Now,Pandora Radio,Stream,US
2,2017-10-16,2017-08-15,2.0,0.000773,0.001547,ushm21787658,191924100799,infinitygirl,Stop Being on My Side,Infinity Girl,Poppyblush,Pandora Radio,Stream,US
3,2017-10-16,2017-08-15,40.0,0.000773,0.030940,ushm21787662,191924100799,infinitygirl,Stop Being on My Side,Infinity Girl,It's Easier Seeing You Now,Pandora Radio,Stream,US
4,2017-10-16,2017-08-15,36.0,0.000773,0.027846,ushm21787666,191924100799,infinitygirl,Stop Being on My Side,Infinity Girl,Pulling a Smile from a Drawer,Pandora Radio,Stream,US

In [2]:
df.drop(['Isrc','Barcode','CDBabySku'], axis='columns', inplace=True)
df.Quantity = df.Quantity.astype(int)
df.head()

,Report Date,Sales Date,Quantity,Price,Subtotal,Album Name,Artist Name,Track Name,Partner Name,Transaction Type,Delivery Country
0,2017-10-16,2017-08-15,7,0.000773,0.005415,Stop Being on My Side,Infinity Girl,Walking Around,Pandora Radio,Stream,US
1,2017-10-16,2017-08-15,1,0.000773,0.000773,Stop Being on My Side,Infinity Girl,By Now,Pandora Radio,Stream,US
2,2017-10-16,2017-08-15,2,0.000773,0.001547,Stop Being on My Side,Infinity Girl,Poppyblush,Pandora Radio,Stream,US
3,2017-10-16,2017-08-15,40,0.000773,0.030940,Stop Being on My Side,Infinity Girl,It's Easier Seeing You Now,Pandora Radio,Stream,US
4,2017-10-16,2017-08-15,36,0.000773,0.027846,Stop Being on My Side,Infinity Girl,Pulling a Smile from a Drawer,Pandora Radio,Stream,US

In [3]:
df['Artist Name'] = 'Band Name'
df.head()

,Report Date,Sales Date,Quantity,Price,Subtotal,Album Name,Artist Name,Track Name,Partner Name,Transaction Type,Delivery Country
0,2017-10-16,2017-08-15,7,0.000773,0.005415,Stop Being on My Side,Band Name,Walking Around,Pandora Radio,Stream,US
1,2017-10-16,2017-08-15,1,0.000773,0.000773,Stop Being on My Side,Band Name,By Now,Pandora Radio,Stream,US
2,2017-10-16,2017-08-15,2,0.000773,0.001547,Stop Being on My Side,Band Name,Poppyblush,Pandora Radio,Stream,US
3,2017-10-16,2017-08-15,40,0.000773,0.030940,Stop Being on My Side,Band Name,It's Easier Seeing You Now,Pandora Radio,Stream,US
4,2017-10-16,2017-08-15,36,0.000773,0.027846,Stop Being on My Side,Band Name,Pulling a Smile from a Drawer,Pandora Radio,Stream,US

In [6]:
albums = df['Album Name'].unique()
for i, album in enumerate(albums):
    cur_df = df[df['Album Name'] == album]
    tracks = cur_df['Track Name'].unique()
    df.loc[df['Album Name'] == album, 'Album Name'] = 'Album_' + str(i+1)
    for j, track in enumerate(tracks):
        df.loc[df['Track Name'] == track, 'Track Name'] = 'Track_' + str(i+1) + '_' + str(j+1)
        
df.head()

,Report Date,Sales Date,Quantity,Price,Subtotal,Album Name,Artist Name,Track Name,Partner Name,Transaction Type,Delivery Country
0,2017-10-16,2017-08-15,7,0.000773,0.005415,Album_3,Band Name,Track_3_1,Pandora Radio,Stream,US
1,2017-10-16,2017-08-15,1,0.000773,0.000773,Album_3,Band Name,Track_3_2,Pandora Radio,Stream,US
2,2017-10-16,2017-08-15,2,0.000773,0.001547,Album_3,Band Name,Track_3_3,Pandora Radio,Stream,US
3,2017-10-16,2017-08-15,40,0.000773,0.030940,Album_3,Band Name,Track_3_4,Pandora Radio,Stream,US
4,2017-10-16,2017-08-15,36,0.000773,0.027846,Album_3,Band Name,Track_3_5,Pandora Radio,Stream,US

In [ ]:
# Save data